// Generated by scripts/sync_pinterest_board.ts - DO NOT EDIT MANUALLY
// Initial placeholder until sync script is run with Pinterest credentials

export interface SlideItem {
  src: string;
  width: number;
  height: number;
  animated: boolean;
}

export const slideshowSlides: SlideItem[] = [];
